services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file:
      - .env.dev
    ports:
      - "${VITE_BACKEND_PORT}:${VITE_BACKEND_PORT}"
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --reload --port ${VITE_BACKEND_PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env.dev
    environment:
      - WATCHPACK_POLLING=true
