services:
  backend:
    build:
      context: ./backend
    ports:
      - "${VITE_BACKEND_PORT}:${VITE_BACKEND_PORT}"
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port ${VITE_BACKEND_PORT}"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_BACKEND_PORT: ${VITE_BACKEND_PORT}
    ports:
      - "${FRONTEND_PORT}:80"
    
